from . import system_wizards
from . import svn_wizards
from . import addon_wizards
from . import cmd_wizards
from . import docker_wizards
from . import module_wizards
from . import database_wizards
from . import git_wizard
from . import test_wizard
from . import feedback_wizards